2017-07-22 14:51:28,496 | INFO     | main.py              | line:112 | STARTING NEW MISSION.
2017-07-22 14:51:28,496 | INFO     | main.py              | line:117 | Accepting connection on tcp:127.0.0.1:1234
2017-07-22 14:51:28,497 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
2017-07-22 14:51:33,498 | DEBUG    | core.py              | line:327 | No connection attempted
2017-07-22 14:51:33,499 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
2017-07-22 14:51:38,501 | DEBUG    | core.py              | line:327 | No connection attempted
2017-07-22 14:51:38,502 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
2017-07-22 14:51:43,506 | DEBUG    | core.py              | line:327 | No connection attempted
2017-07-22 14:51:43,507 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
2017-07-22 14:51:48,511 | DEBUG    | core.py              | line:327 | No connection attempted
2017-07-22 14:51:48,511 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
2017-07-22 14:51:53,515 | DEBUG    | core.py              | line:327 | No connection attempted
2017-07-22 14:51:53,515 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
2017-07-22 14:51:58,516 | DEBUG    | core.py              | line:327 | No connection attempted
2017-07-22 14:51:58,516 | INFO     | core.py              | line:318 | Waiting for Dronology connection.
